package de.hft_stuttgart.ip1;

import de.hft_stuttgart.ip1.actions.CommonAction;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

public class MandelbrotMainFrame {
    JFrame parent;
    private JScrollPane scrollPane;
    private JPanel mandelbrotPanel;
    private JLabel template;

    public MandelbrotMainFrame(JFrame parent) {
        this.parent = parent;
        $$$setupUI$$$();
        loadMenu();
        createUIComponents();


        parent.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                mandelbrotPanel.repaint();
                mandelbrotPanel.validate();
            }
        });

        mandelbrotPanel.repaint();
    }

    private void loadMenu() {
        parent.setJMenuBar(new JMenuBar());
        CommonAction.initActions(parent);
    }

    private void createUIComponents() {
        mandelbrotPanel = new MandelbrotLargePanel();
        scrollPane.add(mandelbrotPanel);
        scrollPane.setViewportView(mandelbrotPanel);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        scrollPane = new JScrollPane();
        scrollPane.setPreferredSize(new Dimension(403, 403));
        scrollPane.setVerticalScrollBarPolicy(20);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return scrollPane;
    }

}
